import os
from pathlib import Path

# Base paths (relative to this script's directory)
_SCRIPT_DIR = Path(__file__).parent

# ============================================================================
# §5 Base Constants (DESIGN.md)
# ============================================================================
import pandas as pd

SEED = 42
TOP_K = 5

# 2026-07-17: pool expanded from 30 (topic/mfcc_analysis subset) to the full 661-song
# catalog (full_catalog_songs.csv, derived from data/songs_master.csv) -- the 30-song
# Stage 2 round showed the small pool couldn't represent enough themes to pick well.
SONGS_CSV = _SCRIPT_DIR / "full_catalog_songs.csv"
SAMPLE_TAGS = pd.read_csv(SONGS_CSV)["tag"].tolist()

# Stems for the full catalog live in this folder's own work/ (not
# topic/mfcc_analysis/stems, which is deliberately capped at 30 songs -- see its
# README.md). Generated by 07_prepare_full_stems.py.
STEMS_DIR = _SCRIPT_DIR / "work/stems_full/htdemucs"

# ASR -- GPU available on this machine (RTX 4080 SUPER), so use the DESIGN.md §5
# defaults (large-v3 / float16) instead of the CPU-bound §7 override.
WHISPER_MODEL = os.environ.get("WHISPER_MODEL", "large-v3")
WHISPER_DEVICE = os.environ.get("WHISPER_DEVICE", "cuda")
WHISPER_COMPUTE = os.environ.get("WHISPER_COMPUTE", "float16")
# faster-whisper parameters (no change needed):
#   language=None, vad_filter=True, temperature=0.0,
#   condition_on_previous_text=False, beam_size=5

# Embedding
EMBED_MODEL = "BAAI/bge-m3"
# Fallback: intfloat/multilingual-e5-small

# LLM (Groq)
# 2026-07-17: Stage 1 full-catalog profiling burned through two models' daily quotas
# in one session -- llama-3.3-70b-versatile (100k TPD, hit at song 126/661), then
# openai/gpt-oss-120b (200k TPD, hit at song 327/661). Each Groq model has its own
# separate TPD bucket, so switching model unblocks immediately; spot-check
# format/Korean output before each switch. Now on meta-llama/llama-4-scout-17b-16e-
# instruct. If this also exhausts, next candidates: qwen/qwen3-32b, qwen/qwen3.6-27b
# (avoid openai/gpt-oss-20b -- that's the deployed backend's model).
GROQ_MODEL = os.environ.get("GROQ_MODEL", "meta-llama/llama-4-scout-17b-16e-instruct")
GROQ_TEMPERATURE = 0.0

# §7 Override: GROQ_API_KEY from env or work/groq.key file
def get_groq_api_key():
    """Load GROQ_API_KEY from environment or work/groq.key file."""
    api_key = os.environ.get("GROQ_API_KEY")
    if api_key:
        return api_key
    key_file = _SCRIPT_DIR / "work/groq.key"
    if key_file.exists():
        return key_file.read_text().strip()
    raise ValueError(
        "GROQ_API_KEY not found. Set env GROQ_API_KEY or create work/groq.key"
    )

GROQ_API_KEY = None  # Will be loaded on demand in scripts

# Evaluation queries: 4 categories x 2 levels (L1, L4) = 8 queries
# LEGACY (2026-07-17 - DESIGN.md Section 1b): unused until Stage 2 runs. Categories
# are now generated dynamically from song_profiles.csv's keyword_main/keyword_sub.
# Kept as reference for Stage 2's query-expansion template design.
CATEGORIES = {
    "C1": "슬픔/우울",
    "C2": "가련함/나아감",
    "C3": "힙함/세련됨/시티팝",
    "C4": "밝음/아침/위로",
}

PROMPTS = {
    "C1-L1": "우울하고 슬픈 노래 틀어줘.",
    "C1-L4": "짙은 밤하늘 아래 홀로 남겨진 듯한 고독감이 밀려오지만, 애써 담담하게 슬픔을 받아들이며 조용히 내면을 위로하는 애절하고 서정적인 정서.",
    "C2-L1": "희망찬데 슬픈 노래.",
    "C2-L4": "금방이라도 부서질 것처럼 연약하고 서글픈 보컬의 목소리 뒤로, 세차게 몰아치는 드럼과 기타 사운드가 질주하며 불안 속에서도 끝내 딛고 일어나 나아가고자 하는 아련하고 가련한 의지.",
    "C3-L1": "힙하고 세련된 노래.",
    "C3-L4": "지나치게 무겁지 않은 미디엄 템포 위에 재지(Jazzy)한 건반과 찰진 베이스 리듬이 얹혀, 도회적인 고독과 낭만이 교차하는 감각적이고 스타일리시한 무드.",
    "C4-L1": "아침에 듣기 좋은 밝은 노래.",
    "C4-L4": "이른 아침의 맑은 공기와 부드러운 햇살이 스며들 듯, 어쿠스틱한 악기들이 만드는 포근한 공간감 속에서 불안을 걷어내고 긍정적인 온기를 불어넣는 나른하면서도 화사한 순간.",
}

# Stage 1 (DESIGN.md Section 1b, 6-02b): per-song lyrics profiling prompt. Unlike
# PROMPTS/CATEGORIES above, this does not generate search text -- it generates a
# per-song label (desc/keyword_main/keyword_sub) for human QC scoring.
# 2026-07-17 개정: Stage 1 QC(14곡) 결과 main/sub 순위가 29%(4/14)에서 뒤바뀐 것으로
# 지적됨(notes/03-stage1-handoff.md). n=14로는 원인(메타포 이해 부족 등) 검증이 무리라고
# 판단, 순위를 매기지 않고 category1/category2로 대등하게 뽑도록 프롬프트를 바꿨다(절충안
# 1안 채택 -- 원인 조사는 pool 확장 후 후속 과제로 보류).
PROFILE_PROMPT = """다음은 어느 노래의 가사다(일본어 또는 영어), 여러 문장/구절로 이루어져 있다.

1. 가사를 문장(또는 절) 단위로 끊어 각 문장에서 느껴지는 감정을 파악하라(이 분석 과정
   자체는 출력하지 않는다).
2. 문장별 감정을 종합해, 이 곡 전체를 지배하는 감정과 서사를 한국어 한 문장으로 요약하라.
3. 그 요약 문장에서 두드러지는 감정/분위기 키워드 2개를 뽑아라. 두 키워드 사이에 우선순위를
   매기지 말 것 — 곡을 대표하는 감정 쌍으로 대등하게 취급한다.

규칙: 가사 원문의 문장이나 구절을 그대로 인용·번역하지 말 것. 곡 제목·아티스트명·고유명사를
쓰지 말 것. 키워드는 명사 또는 형용사 단어 하나씩만(구·문장 금지). 사운드·템포·악기에 대한
묘사는 쓰지 말 것(감정과 상황만).

출력 형식(반드시 이 3줄 형식으로만 출력):
DESC: <한국어 한 문장>
CATEGORY1: <키워드 1개>
CATEGORY2: <키워드 1개>

가사:
{lyrics}"""

# Stage 1 fallback (used only when work/transcripts/<tag>.txt is unavailable on this
# machine -- see README.md "프로파일 QC 채점 가이드" note on 2026-07-17 run provenance).
# Takes texts_summary.csv's mood summary as input instead of raw ASR lyrics. This is a
# lower-fidelity proxy for PROFILE_PROMPT (summary-of-a-summary, not sentence-level
# analysis of the actual lyrics) -- re-run with PROFILE_PROMPT against real transcripts
# once available.
PROFILE_PROMPT_FROM_SUMMARY = """다음은 어느 노래의 정서·분위기·에너지를 요약한 문장들이다
(LLM이 원곡 가사를 바탕으로 미리 생성한 것 -- 가사 원문이 아니다).

1. 이 요약 문장들을 하나씩 살펴 그 안에 담긴 감정을 파악하라(이 분석 과정 자체는 출력하지
   않는다).
2. 종합해서, 이 곡 전체를 지배하는 감정과 서사를 한국어 한 문장으로 다시 요약하라 -- 단,
   입력 문장을 그대로 옮기지 말고 감정·상황 중심으로 재구성할 것.
3. 그 요약 문장에서 두드러지는 감정/분위기 키워드 2개를 뽑아라. 두 키워드 사이에 우선순위를
   매기지 말 것 -- 곡을 대표하는 감정 쌍으로 대등하게 취급한다.

규칙: 입력 문장을 그대로 옮기지 말 것. 곡 제목·아티스트명·고유명사를 쓰지 말 것. 키워드는
명사 또는 형용사 단어 하나씩만(구·문장 금지). 사운드·템포·악기·질감에 대한 묘사(예:
'몽환적', '질주감', '공격적')는 쓰지 말 것 -- 감정과 상황만 남길 것.

출력 형식(반드시 이 3줄 형식으로만 출력):
DESC: <한국어 한 문장>
CATEGORY1: <키워드 1개>
CATEGORY2: <키워드 1개>

요약문:
{summary}"""

# Stage 2 (2026-07-17, post-Stage1-30song-QC): difficulty-tiered natural-language
# queries chosen by the researcher instead of frequency-derived category anchors.
# T1 = literal emotion words, T2 = idiomatic/slang emotion expressions, T3 =
# metaphorical/scenario descriptions with no explicit emotion word. Song-side text
# is song_profiles.csv's `desc` (Stage 1 output) -- no raw/summary/keyword arm
# comparison this round, just "does desc-based search satisfy a real request."
STAGE2_QUERIES = {
    "T1-Q1": {"tier": "T1_literal", "text": "행복한 노래 틀어줘."},
    "T1-Q2": {"tier": "T1_literal", "text": "슬픈 노래 틀어줘."},
    "T2-Q1": {"tier": "T2_idiomatic", "text": "요즘 좀 꿀꿀해. 그런 기분에 어울리는 노래 틀어줘."},
    "T2-Q2": {"tier": "T2_idiomatic", "text": "날아갈 것처럼 신나는 기분이야. 그런 노래 틀어줘."},
    "T3-Q1": {"tier": "T3_metaphorical", "text": "먼저 떠난 이가 불러주는 듯한 위로의 노래를 듣고 싶어."},
    "T3-Q2": {"tier": "T3_metaphorical", "text": "부드럽고 포근한 자장가 같은 노래를 듣고 싶어."},
}
STAGE2_TOP_K = 3  # pool is only 30 songs -- top-15 was half the catalog, too loose

# Output directory
OUT_DIR = _SCRIPT_DIR / "out"

# Work directory
WORK_DIR = _SCRIPT_DIR / "work"
